//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaMVCWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto_Cliente
    {
        public int ID { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<int> ID_Tipo { get; set; }
        public string Valor { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tipo_Contacto Tipo_Contacto { get; set; }
    }
}
